version: '3.8'

services:
  user-service:
    build: 
      context: ./user-service
    container_name: user-service
    ports:
      - "50051:50051"
  
  api-gateway:
    build:
      context: ./api-gateway
    container_name: api-gateway
    ports:
      - "8080:8080"
    depends_on:
      - user-service